name: my_video_project
description: A clean, high-performance video streaming app.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  # UI & Assets
  cupertino_icons: ^1.0.6
  google_fonts: ^8.0.0
  # State Management
  provider: ^6.1.1
  # Networking & Caching
  cached_network_image: ^3.3.1
  http: ^1.2.0
  connectivity_plus: ^7.0.0
  # System & Utils
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  # Video Core
  media_kit: ^1.1.10
  media_kit_video: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/ads/
